name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Tylko PR-y, które kierują się na main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v5

      - name: Approve PR (required for some repos)
        if: success()
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge PR
        if: success()
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}